### ISSUE TITLE
Extension doesn't have a name in nemo preferences

### ISSUE THREAD

**Issue by chrisjbillington** [chrisjbillington/git_nautilus_icons#18]
As @Niklas81 points out in #17, in nemo's preferences, the extension shows up as `InfoProvider+NemoPython no information available`.

I don't know how to set the name such that it will show up with something sensible here. If anyone knows how, I'll fix it.

![image](https://user-images.githubusercontent.com/1044087/111052023-68182000-8425-11eb-9f87-99935ec41876.png)

**Comment by chrisjbillington** [comment]
I figured out how to make it show at least something:

![image](https://user-images.githubusercontent.com/1044087/111052315-bf1ef480-8427-11eb-97fe-c73f1749846f.png)

Don't know how to get it to show more. This will have to do for now!

**Comment by ghost** [comment]
By looking at the plugin `compare`, I find this at the very end of the main plugin file `src/nemo-compare.py`, see https://github.com/linuxmint/nemo-extensions/blob/master/nemo-compare/src/nemo-compare.py. It's this bit:
```python
    def get_name_and_desc(self):
        return [("Nemo Compare:::Allows file comparison from the context menu:::nemo-compare-preferences")]
```
The last bit, `:::nemo-compare-preferences`, reffers to the command to be executed to launch an external program to handle it's configuration. If you don't have that, you could probably just remove that whole part or keep the `:::` bit.
