### ISSUE TITLE
Icons have a super low resolution

### ISSUE THREAD

**Issue by depau** [chrisjbillington/git_nautilus_icons#4]
I have an HiDPI display and the icons look veeery pixelated. Is it possible to have some higher resolution icons? I can't find any SVG source file.

**Comment by chrisjbillington** [comment]
Ah, no, the icons are bitmaps that are generated by programatically joining together the 'subicons', which are also bitmaps (and they are pretty small bitmaps seeing as I want to be able to squish 4 'subicons' into each icon in order to show all the status information).

I've been planning on making them SVGs and programatically joining them using some SVG library, but I haven't done this yet.

**Comment by chrisjbillington** [comment]
I've updated the icons to be svgs. They are not the prettiest icons ever, but it should be an improvement. Could you let me know if it looks better on the high DPI display?

**Comment by depau** [comment]
Now they don't show up at all lol

**Comment by depau** [comment]
Maybe you should simply provide the bitmaps (i.e. use inkscape to raster-ize them), but also provide a 48x48 version as 24x24@2x like some themes do.

**Comment by depau** [comment]
Now I see why: the generated files are empty. I'll look into the generation script

**Comment by depau** [comment]
![Screenshot](https://s9.postimg.org/a342pgqqn/Screenshot_from_2018-02-23_11-26-33.png)
🤔🤔🤔🤔

**Comment by depau** [comment]
Much better now!
![Screenshot](https://s9.postimg.org/swpvmgh8v/Screenshot_from_2018-02-23_11-33-55.png)

Thank you!

**Comment by chrisjbillington** [comment]
Thanks and well spotted! 

I was just copying example code from the svgutils docs that used strings with 'cm' in the size, and I changed it to 'px' and it worked...not sure why that makes any difference (worked for me!) but glad it's fixed for you!

**Comment by depau** [comment]
I tried to save it from Inkscape as optimized SVG and the plugin complained about an unrecognized "px" string.
*There it is* 😅
