### ISSUE TITLE
Installation instructions: python3-gi

### ISSUE THREAD

**Issue by nicolas-raoul** [chrisjbillington/git_nautilus_icons#6]
For Ubuntu 18.04, I believe that installing `python3-gi` is necessary too.

**Comment by chrisjbillington** [comment]
Thanks for the report!

It looks like you're correct, except that it should presumably be `python-gi`, not `python3-gi` since nautilus appears to be running extensions in Python 2 in Ubuntu 18.04.

I'll add it to the instructions.

**Comment by chrisjbillington** [comment]
Done :)

**Comment by nicolas-raoul** [comment]
Thanks :-)
